require_relative 'BeerBot/00.utils/utils'
require_relative 'BeerBot/00.utils/paramExpand'
require_relative 'BeerBot/00.utils/DataFile'
require_relative 'BeerBot/00.utils/InOut'
require_relative 'BeerBot/00.utils/world/IRCWorld'
require_relative 'BeerBot/01.connect/IRCConnection'
require_relative 'BeerBot/01.protocols/botmsg'
require_relative 'BeerBot/01.protocols/irc'
require_relative 'BeerBot/02.bot/bot'
require_relative 'BeerBot/03.more/BotMsgMore'
require_relative 'BeerBot/06.dispatchers/irc'
require_relative 'BeerBot/70.scheduler/scheduler'

require_relative '../modules/init.rb'
